name: App CI/CD (ECR + Helm)

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'helm/**'
      - '.github/workflows/app-cicd.yaml'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read ECR URL from secrets
        run: |
          echo "ECR_URL=${{ secrets.ECR_URL }}" >> $GITHUB_ENV

      - name: Login to ECR
        env:
          ECR_URL: ${{ env.ECR_URL }}
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin "$ECR_URL"

      - name: Build & Push
        env:
          ECR_URL: ${{ env.ECR_URL }}
        run: |
          docker build -t "$ECR_URL:latest" ./app
          docker push "$ECR_URL:latest"

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name hello-eks --region eu-central-1

      - name: Deploy via Helm
        run: |
          helm upgrade --install hello ./helm/hello-chart \
            --namespace default \
            --set image.repository=$ECR_URL \
            --set image.tag=latest
